// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.my.gae.client.managed.ui;

import com.google.gwt.text.shared.AbstractRenderer;
import com.my.gae.client.managed.request.ApplicationEntityTypesProcessor;
import com.my.gae.client.proxy.PersonProxy;
import com.my.gae.client.scaffold.place.ProxyListPlace;

public abstract class ApplicationListPlaceRenderer_Roo_Gwt extends AbstractRenderer<ProxyListPlace> {

    public String render(ProxyListPlace object) {
        return new ApplicationEntityTypesProcessor<String>() {

            @Override
            public void handlePerson(PersonProxy isNull) {
                setResult("Persons");
            }
        }.process(object.getProxyClass());
    }
}
