// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.my.gae.client.managed.activity;

import com.google.gwt.place.shared.Place;
import com.google.gwt.place.shared.PlaceController;
import com.google.gwt.view.client.Range;
import com.google.web.bindery.requestfactory.shared.Receiver;
import com.google.web.bindery.requestfactory.shared.Request;
import com.my.gae.client.managed.request.ApplicationRequestFactory;
import com.my.gae.client.proxy.PersonProxy;
import com.my.gae.client.scaffold.ScaffoldMobileApp;
import com.my.gae.client.scaffold.activity.IsScaffoldMobileActivity;
import com.my.gae.client.scaffold.place.AbstractProxyListActivity;
import com.my.gae.client.scaffold.place.ProxyListView;
import java.util.List;

public abstract class PersonListActivity_Roo_Gwt extends AbstractProxyListActivity<PersonProxy> implements IsScaffoldMobileActivity {

    protected ApplicationRequestFactory requests;

    public PersonListActivity_Roo_Gwt(PlaceController placeController, ProxyListView<com.my.gae.client.proxy.PersonProxy> view, Class<com.my.gae.client.proxy.PersonProxy> proxyType) {
        super(placeController, view, proxyType);
    }

    protected void fireCountRequest(Receiver<java.lang.Long> callback) {
        requests.personRequest().countPeople().fire(callback);
    }
}
